language: python
python:
 - "3.6"


install:
  - pip install -r requirements.txt


script:
  - pytest
  - coverage run --source=app -m pytest && coverage report

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - coveralls
